{% set name = "cliff" %}
{% set version = "3.5.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "5bfb684b5fcdff0afaaccd1298a376c0e62e644c46b7e9abc034595b41fe1759" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  build:
    - python >=3.6
    - pip
    - pbr !=2.1.0,>=2.0.0

  run:
    - python >=3.6
    - pbr !=2.1.0,>=2.0.0
    - cmd2 !=0.8.3
    - prettytable >=0.7.2
    - pyparsing >=2.1.0
    - six >=1.10.0
    - stevedore >=2.0.1
    - pyyaml >=3.12

test:
  imports:
    - cliff
    - cliff.app
    - cliff.commandmanager
    - cliff.command
    - cliff.interactive

about:
  home: https://github.com/openstack/cliff
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Command Line Interface Formulation Framework
  dev_url: http://git.openstack.org/cgit/openstack/cliff
  doc_url: http://docs.openstack.org/developer/cliff

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - amatthies
    - tschoonj
