{% set name = "cliff" %}
{% set version = "2.9.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "ab50fbb4717c74e32915123f4150805b463e81de1d58e43996fd813b26c5b447" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools
    - pbr !=2.1.0,>=2.0.0

  run:
    - python
    - cmd2 >=0.6.7
    - prettytable <0.8,>=0.7.1
    - pyparsing >=2.1.0
    - six >=1.9.0
    - stevedore >=1.20.0
    - unicodecsv >=0.8.0  # [not py3k]
    - pyyaml >=3.10.0

test:
  imports:
    - cliff
    - cliff.app
    - cliff.commandmanager
    - cliff.command
    - cliff.interactive

about:
  home: https://github.com/openstack/cliff
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Command Line Interface Formulation Framework'
  dev_url: http://git.openstack.org/cgit/openstack/cliff
  doc_url: http://docs.openstack.org/developer/cliff

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - amatthies
