{% set name = "cliff" %}
{% set version = "2.12.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "7c502ef59ad7acbb32d25b74a732794638f3db5d35b454f05a4cf9c302587188" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pbr !=2.1.0,>=2.0.0

  run:
    - python
    - pbr !=2.1.0,>=2.0.0
    - cmd2 !=0.8.3,<0.9.0  # [py2k]
    - cmd2 !=0.8.3  # [py3k]
    - prettytable <0.8,>=0.7.2
    - pyparsing >=2.1.0
    - six >=1.10.0
    - stevedore >=1.20.0
    - unicodecsv >=0.8.0  # [py2k]
    - pyyaml >=3.12

test:
  imports:
    - cliff
    - cliff.app
    - cliff.commandmanager
    - cliff.command
    - cliff.interactive

about:
  home: https://github.com/openstack/cliff
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Command Line Interface Formulation Framework'
  dev_url: http://git.openstack.org/cgit/openstack/cliff
  doc_url: http://docs.openstack.org/developer/cliff

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - amatthies
