appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: pNqy8UyDGLxMStqWaV6D9vmxRMa3DXOO30FLXEK1I7vQSo/QpnjaoqVL2hMNn22RnrcMjPniGqmdD5otRBG2mWUeEHDglsvS4uL3ghrn5UG4FzJqE1HMoMk9arJ5fYCTaCMGG0o6cB412/14FKBl5VSCmyKuw1aUidQykTe1dnAVIugEOm14KOWbP4QtYiGymVNKO+36PKQ7ZUFEwLfaMRc3QBCoVCf24BnxfYfHrM706IhSGz8wo9P01YwpXmM5BQcnN3GW+YaAfRtxA72lIyLBdX0LOtp3uLXvqLPNXO5ejy6hq9ZOvK0z6+/hxKyzaiwzVu4dNQqtOMJvcybTy/MPKL3//MHgOFaU/Q7aCMePushyozBL9pJ4CT/SD9oUPMoOkOMAAOETPXhGgz5/OZC+XymvWFqk/r5j1aMhJIpSgKKedd9aFF7tosEL2heCHDjR2U8xm43p/Q2wsn4P3933qmMy2pf7bR/TdI4NlVys4EtlDOGEqdEmaiCwCY+PGLYv60w3NoviVUIfM2zpcvUWxoBfNtrumLUpehoM5MpUVPHGSMEt8nv7CWyWgAW+bN7CzbTPjnWbJEmj/BrNzeCxQuZYdzTAitd3VasRBey5a+Hd1lx1uIiZFCofm456PgQihXvxQDII4CTf0WVzjC2HDnHfziMybC2Z/9tpSPc=}
provider:
  win: azure
conda_forge_output_validation: true
